### ISSUE TITLE
Port issue when installing JIRA in Linux machine

### ISSUE THREAD

**Issue by sundararajanr** [DevOpsPracticeSessions/JIRA#1]
Jenkins and JIRA uses the same port as 8080. Need to change the port for JIRA while doing the installation.

**Comment by karthikgreen1** [comment]
after  changing the port  for Jenkins , now  able to install Jira , in that port 8080 and its working fine 

Let's change a port on which Jenkins runs:
1. If you run Jenkins using the command line, then you can execute a
command such as java -jar -httpPort=9999 jenkins.war to change the
existing port from 8080 to 9999.
2. Another way to change the port while Jenkins is installed using the
Windows package is as follows:
Go to the Program Files/Jenkins directory where you installed
Jenkins
Open the Jenkins.xml in the editor
Find "--httpPort=8080" and replace the port 8080 with the new port
number

**Comment by sundararajanr** [comment]
Below is the suggestion to resolve the port issue for JIRA and JENKINS.
Let's change a port on which Jenkins runs:
1. If you run Jenkins using the command line, then you can execute a
command such as java -jar -httpPort=9999 jenkins.war to change the
existing port from 8080 to 9999.
2. Another way to change the port while Jenkins is installed using the
Windows package is as follows:
Go to the Program Files/Jenkins directory where you installed
Jenkins
Open the Jenkins.xml in the editor
Find "--httpPort=8080" and replace the port 8080 with the new port
number

**Comment by kradhak** [comment]
In case if issue not resolved try this as well
to assign port
nc -k -l XXXX
